[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
colored = "2.0.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
dotenv = "0.15.0"
md5 = "0.7.0"
fancy-regex = "0.10.0"
pathfinding = "4.0.0"